import { expect, test } from '@playwright/test'

test('commits each completed field immediately with independent undo and redo', async ({
  page
}) => {
  test.setTimeout(60_000)
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByText('空間模型已就緒')).toBeVisible()
  const length = page.getByLabel('溫室縱向深度', { exact: true })
  const width = page.getByLabel('單棟寬度', { exact: true })
  await length.fill('12.7')
  await length.press('Enter')
  await expect(
    page.getByRole('button', { name: '復原 ⌘Z', exact: true })
  ).toBeEnabled()
  await width.fill('8')
  await width.press('Tab')
  await expect(width).toHaveValue('8')
  await page.getByRole('button', { name: '復原 ⌘Z', exact: true }).click()
  await expect(width).toHaveValue('7')
  await expect(length).toHaveValue('12.7')
  await page.getByTestId('scene').focus()
  await page.keyboard.press('Meta+Shift+z')
  await expect(width).toHaveValue('8')
  await page.keyboard.press('Meta+z')
  await expect(width).toHaveValue('7')
  await page.getByRole('button', { name: '重做 ⇧⌘Z', exact: true }).click()
  await expect(width).toHaveValue('8')
  await page.getByRole('button', { name: '上移第 2 項', exact: true }).click()
  await expect(page.getByLabel('第 1 項種類')).toHaveValue('drain')
  await page.getByRole('button', { name: '復原 ⌘Z', exact: true }).click()
  await expect(page.getByLabel('第 1 項種類')).toHaveValue('soil')
  const bottom = page.getByLabel('拉網最低位置', { exact: true })
  await bottom.fill('4')
  await bottom.press('Enter')
  await expect(page.getByRole('alert')).toContainText('底部高度')
  await expect(bottom).toHaveValue('0.45')
  await bottom.fill('')
  await bottom.press('Tab')
  await expect(bottom).toHaveValue('0.45')
  await page.getByRole('button', { name: '復原 ⌘Z', exact: true }).click()
  await expect(width).toHaveValue('7')
  expect(errors).toEqual([])
})
